
spring:
  datasource:
    username: admin
    password: 123456qwe
    url: jdbc:mysql://car-board-qa-rds.cnt5onsawglw.ap-northeast-2.rds.amazonaws.com:3306/car_board

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        # show_sql: true

logging:
  level:
    com.carboard: debug
    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace
    org.springframework.web: debug